name: Publish PaddleLabel-ML to pypi

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Get default weights
        run: |
          cd ..
          pwd
          ls

          wget https://github.com/linhandev/static/releases/download/v0.0.2/EISeg.zip
          unzip EISeg.zip
          mkdir -p ./PaddleLabel-ML/paddlelabel_ml/model/eiseg/ckpt/
          mv ./EISeg/* ./PaddleLabel-ML/paddlelabel_ml/model/eiseg/ckpt/

          wget https://github.com/linhandev/static/releases/download/v0.0.2/PicoDet.zip
          unzip PicoDet.zip
          mkdir -p ./PaddleLabel-ML/paddlelabel_ml/model/PicoDet/ckpt/
          mv ./PicoDet/* ./PaddleLabel-ML/paddlelabel_ml/model/PicoDet/ckpt/

          cd PaddleLabel-ML

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install twine wheel
      #     if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Bump version
        run: |
          python tool/bumpversion.py

      - name: Config basic git info
        run: git config --global user.email "bot@github.com" && git config --global user.name "Action Bot"

      - name: Update version
        run: git add paddlelabel_ml/version; git commit -m "publish ci bump version"; git push

      - name: Build package
        run: |
          python setup.py sdist bdist_wheel

      - name: Inspect files
        run: |
          tree paddlelabel_ml/model/eiseg
          tree paddlelabel_ml/model/PicoDet

      - name: Save built package
        uses: actions/upload-artifact@v3
        with:
          name: PaddleLabel-ML_built_package
          path: |
            dist

      # - name: Publish to PyPI
      #   uses: pypa/gh-action-pypi-publish@release/v1
      #   with:
      #     user: __token__
      #     password: ${{ secrets.PADDLELABEL_ML_PUBLISH_API_TOKEN }}
